[build]
  base = "client"
  command = "npx expo export --platform web"
  publish = "dist"

[build.environment]
  EXPO_PUBLIC_BACKEND_BASE_URL = "https://server-production-454c.up.railway.app"
  NODE_VERSION = "20"