import { StyleSheet, Platform } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    scrollContent: {
      flexGrow: 1,
      backgroundColor: theme.backgroundRoot,
    },
    header: {
      marginBottom: Spacing.xl,
      overflow: 'hidden',
    },
    headerContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: Spacing.lg,
      paddingTop: Spacing.xl,
      paddingBottom: Spacing.lg,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundTertiary,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
    },
    logoIcon: {
      width: 56,
      height: 56,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.primary,
      justifyContent: 'center',
      alignItems: 'center',
      boxShadow: '0px 4px 12px rgba(22, 120, 209, 0.3)',
    },
    title: {
      fontWeight: '700' as const,
      marginBottom: Spacing.xs,
    },
    subtitle: {
      fontSize: 14,
      color: theme.textSecondary,
    },
    historyButton: {
      width: 40,
      height: 40,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundTertiary,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    welcomeBanner: {
      backgroundColor: theme.primary,
      marginHorizontal: Spacing.lg,
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.lg,
      borderRadius: BorderRadius.lg,
      marginTop: Spacing.sm,
      boxShadow: '0px 4px 12px rgba(22, 120, 209, 0.2)',
    },
    welcomeText: {
      fontSize: 15,
      fontWeight: '500' as const,
      textAlign: 'center',
    },
    formContainer: {
      paddingHorizontal: Spacing.lg,
      gap: Spacing.lg,
    },
    inputGroup: {
      gap: Spacing.sm,
    },
    label: {
      fontWeight: '600' as const,
      fontSize: 14,
      color: theme.textPrimary,
    },
    input: {
      height: 52,
      backgroundColor: theme.backgroundDefault,
      borderRadius: BorderRadius.lg,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      color: theme.textPrimary,
      borderWidth: 1.5,
      borderColor: theme.border,
      fontSize: 16,
      boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.04)',
    },
    selectTrigger: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.backgroundDefault,
      height: 52,
    },
    triggerText: {
      flex: 1,
      fontSize: 16,
      marginRight: Spacing.sm,
    },
    textArea: {
      height: 100,
      paddingTop: Spacing.md,
      textAlignVertical: 'top',
    },
    supplementaryMaterialInput: {
      height: 140,
    },
    uploadButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.sm,
      paddingVertical: Spacing.md,
      borderWidth: 1.5,
      borderColor: theme.borderLight,
      borderRadius: BorderRadius.lg,
      marginTop: Spacing.sm,
    },
    uploadButtonText: {
      fontSize: 13,
      fontWeight: '500' as const,
    },
    imagePreviewContainer: {
      marginTop: Spacing.md,
    },
    imagePreview: {
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    imageWrapper: {
      width: 120,
      height: 120,
      borderRadius: BorderRadius.lg,
      overflow: 'hidden',
    },
    previewImage: {
      width: '100%',
      height: '100%',
    },
    removeImageButton: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: theme.error,
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: -12,
      marginTop: -12,
    },
    imagePreviewHint: {
      marginTop: Spacing.sm,
    },
    filePreviewContainer: {
      marginTop: Spacing.md,
    },
    filePreview: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    fileIconWrapper: {
      width: 48,
      height: 48,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundTertiary,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: Spacing.md,
    },
    fileInfo: {
      flex: 1,
    },
    fileName: {
      marginBottom: Spacing.xs,
    },
    fileContentPreview: {
      fontSize: 12,
      lineHeight: 16,
    },
    removeFileButton: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: theme.error,
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: Spacing.md,
    },
    filePreviewHint: {
      marginTop: Spacing.sm,
    },

    labelWithButton: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    hint: {
      marginTop: Spacing.xs,
      fontSize: 13,
      color: theme.textMuted,
      lineHeight: 18,
    },
    buttonContainer: {
      marginTop: Spacing.xl,
      paddingHorizontal: Spacing.lg,
      gap: Spacing.md,
      paddingBottom: Spacing['5xl'],
    },
    primaryButton: {
      backgroundColor: theme.primary,
      paddingVertical: Spacing.lg,
      paddingHorizontal: Spacing.xl,
      borderRadius: BorderRadius.lg,
      alignItems: 'center',
      height: 56,
      justifyContent: 'center',
      flexDirection: 'row',
      gap: Spacing.sm,
      boxShadow: '0px 4px 12px rgba(22, 120, 209, 0.35)',
    },
    secondaryButton: {
      backgroundColor: theme.backgroundDefault,
      paddingVertical: Spacing.lg,
      paddingHorizontal: Spacing.xl,
      borderRadius: BorderRadius.lg,
      alignItems: 'center',
      height: 56,
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: theme.border,
      flexDirection: 'row',
      gap: Spacing.sm,
    },
    modalContainer: {
      flex: 1,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContent: {
      width: '90%',
      maxWidth: 500,
      maxHeight: '80%',
      minHeight: 300,
      borderRadius: BorderRadius.lg,
      overflow: 'visible',
      backgroundColor: theme.backgroundDefault,
      flexDirection: 'column',
      flex: 1,
    },
    modalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.lg,
      borderBottomWidth: 1,
      borderBottomColor: theme.borderLight,
      flexShrink: 0,
    },
    modalHeaderLeft: {
      flex: 1,
    },
    modalHeaderRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
    },
    refreshButton: {
      padding: Spacing.xs,
    },
    loadingContainer: {
      paddingVertical: Spacing['2xl'],
      alignItems: 'center',
      gap: Spacing.md,
    },
    loadingText: {
      marginTop: Spacing.md,
    },
    emptyContainer: {
      paddingVertical: Spacing['2xl'],
      alignItems: 'center',
    },
    knowledgePointsList: {
      flex: 1,
      minHeight: 200,
    },
    knowledgePointItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.lg,
      borderBottomWidth: 1,
      borderBottomColor: theme.borderLight,
      borderWidth: 1,
      borderLeftWidth: 4,
      borderColor: theme.borderLight,
    },
    knowledgePointItemSelected: {
      borderLeftColor: theme.primary,
    },
    knowledgePointContent: {
      flex: 1,
      marginRight: Spacing.md,
    },
    knowledgePointHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: Spacing.xs,
    },
    difficultyBadge: {
      backgroundColor: theme.backgroundTertiary,
      paddingHorizontal: Spacing.sm,
      paddingVertical: 2,
      borderRadius: BorderRadius.sm,
    },
    knowledgePointDesc: {
      lineHeight: 18,
    },
    teacherNamesList: {
      flex: 1,
    },
    teacherNameItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: theme.borderLight,
      borderWidth: 1,
      borderLeftWidth: 4,
      borderColor: theme.borderLight,
    },
    teacherNameItemSelected: {
      borderLeftColor: theme.primary,
    },
    deleteButton: {
      width: 32,
      height: 32,
      borderRadius: BorderRadius.md,
      justifyContent: 'center',
      alignItems: 'center',
    },
    customInputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.lg,
      borderTopWidth: 1,
      borderTopColor: theme.borderLight,
    },
    customInput: {
      flex: 1,
      height: 44,
      marginBottom: 0,
    },
    addButton: {
      width: 44,
      height: 44,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.primary,
      justifyContent: 'center',
      alignItems: 'center',
      boxShadow: '0px 2px 8px rgba(22, 120, 209, 0.3)',
    },
    addButtonDisabled: {
      backgroundColor: theme.backgroundTertiary,
      boxShadow: 'none',
    },
    // Date picker styles
    dateDisplay: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.backgroundDefault,
      height: 52,
      paddingHorizontal: Spacing.md,
      borderRadius: BorderRadius.lg,
      borderWidth: 1.5,
      borderColor: theme.border,
      boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.04)',
    },
    calendarIcon: {
      marginLeft: Spacing.md,
    },
    datePickerModalContainer: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'flex-end',
    },
    datePickerModalContent: {
      backgroundColor: theme.backgroundDefault,
      borderTopLeftRadius: BorderRadius.lg,
      borderTopRightRadius: BorderRadius.lg,
      paddingTop: Spacing.lg,
      paddingBottom: Platform.OS === 'ios' ? 34 : Spacing.lg,
    },
    datePickerModalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: Spacing.lg,
      marginBottom: Spacing.lg,
    },
    datePicker: {
      width: '100%',
    },
    // Model selection styles
    modelOptionsContainer: {
      marginTop: Spacing.sm,
    },
    modelOptionsScrollContent: {
      flexDirection: 'row',
      gap: Spacing.sm,
      paddingRight: Spacing.sm,
    },
    modelOption: {
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.md,
      borderRadius: BorderRadius.lg,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.backgroundDefault,
      alignItems: 'center',
      minHeight: 60,
      minWidth: 140,
    },
    modelOptionSelected: {
      borderColor: theme.primary,
    },
    modelOptionName: {
      fontWeight: '600' as const,
      marginBottom: 2,
    },
    modelOptionAdvantage: {
      fontSize: 11,
    },
  });
};
