import { StyleSheet, Platform } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    scrollContent: {
      flexGrow: 1,
      backgroundColor: theme.backgroundRoot,
    },
    header: {
      marginBottom: Spacing.xl,
      overflow: 'hidden',
    },
    headerContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: Spacing.lg,
      paddingTop: Spacing.xl,
      paddingBottom: Spacing.lg,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundTertiary,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
    },
    logoIcon: {
      width: 56,
      height: 56,
      borderRadius: BorderRadius.lg,
      backgroundColor: '#FF6B35',
      justifyContent: 'center',
      alignItems: 'center',
      boxShadow: '0px 4px 12px rgba(255, 107, 53, 0.3)',
    },
    title: {
      fontWeight: '700' as const,
      marginBottom: Spacing.xs,
    },
    subtitle: {
      fontSize: 14,
      color: theme.textSecondary,
    },
    formContainer: {
      paddingHorizontal: Spacing.lg,
      gap: Spacing.lg,
      paddingBottom: Spacing['5xl'],
    },
    inputGroup: {
      gap: Spacing.sm,
    },
    label: {
      fontWeight: '600' as const,
      fontSize: 14,
      color: theme.textPrimary,
    },
    historyButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.sm,
      paddingVertical: Spacing.lg,
      backgroundColor: theme.backgroundDefault,
      borderRadius: BorderRadius.lg,
      borderWidth: 2,
      borderColor: theme.primary,
    },
    historyButtonText: {
      fontSize: 15,
      fontWeight: '600' as const,
    },
    input: {
      height: 52,
      backgroundColor: theme.backgroundDefault,
      borderRadius: BorderRadius.lg,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      color: theme.textPrimary,
      borderWidth: 1.5,
      borderColor: theme.border,
      fontSize: 16,
      boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.04)',
    },
    textArea: {
      height: 120,
      paddingTop: Spacing.md,
      textAlignVertical: 'top',
    },
    uploadButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.sm,
      paddingVertical: Spacing.md,
      borderWidth: 2,
      borderColor: theme.borderLight,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundDefault,
      borderStyle: 'dashed',
    },
    filePreview: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.backgroundDefault,
      padding: Spacing.md,
      borderRadius: BorderRadius.lg,
      borderWidth: 1.5,
      borderColor: theme.border,
    },
    fileIconWrapper: {
      width: 48,
      height: 48,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundTertiary,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: Spacing.md,
    },
    fileInfo: {
      flex: 1,
    },
    removeButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.error,
      justifyContent: 'center',
      alignItems: 'center',
    },
    voiceButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.sm,
      paddingVertical: Spacing.lg,
      backgroundColor: theme.backgroundDefault,
      borderRadius: BorderRadius.lg,
      borderWidth: 2,
      borderColor: theme.borderLight,
    },
    voiceButtonRecording: {
      backgroundColor: theme.error,
      borderColor: theme.error,
    },
    voiceButtonText: {
      fontSize: 15,
      fontWeight: '600' as const,
    },
    transcriptionContainer: {
      marginTop: Spacing.sm,
      padding: Spacing.md,
      backgroundColor: theme.backgroundDefault,
      borderRadius: BorderRadius.lg,
      borderWidth: 1.5,
      borderColor: theme.border,
    },
    transcriptionLabel: {
      marginBottom: Spacing.xs,
      fontWeight: '600' as const,
    },
    generateButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.sm,
      paddingVertical: Spacing.lg,
      backgroundColor: theme.primary,
      borderRadius: BorderRadius.lg,
      marginTop: Spacing.md,
      boxShadow: '0px 4px 12px rgba(22, 120, 209, 0.3)',
    },
    generateButtonText: {
      fontSize: 16,
      fontWeight: '600' as const,
    },
    progressText: {
      textAlign: 'center',
      marginTop: Spacing.md,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: theme.backgroundDefault,
      borderTopLeftRadius: BorderRadius.xl,
      borderTopRightRadius: BorderRadius.xl,
      maxHeight: '80%',
    },
    modalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: Spacing.lg,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    previewContainer: {
      padding: Spacing.lg,
      gap: Spacing.md,
      maxHeight: '60%',
    },
    slidePreview: {
      padding: Spacing.md,
      backgroundColor: theme.backgroundRoot,
      borderRadius: BorderRadius.lg,
      borderWidth: 2,
      borderColor: theme.border,
    },
    slidePreviewActive: {
      borderColor: theme.primary,
      borderWidth: 2.5,
    },
    modalFooter: {
      flexDirection: 'row',
      gap: Spacing.md,
      padding: Spacing.lg,
      borderTopWidth: 1,
      borderTopColor: theme.border,
    },
    exportButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.sm,
      paddingVertical: Spacing.lg,
      backgroundColor: theme.primary,
      borderRadius: BorderRadius.lg,
    },
    exportButtonPDF: {
      backgroundColor: '#FF6B35',
    },
    filterContainer: {
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.lg,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    filterScroll: {
      gap: Spacing.sm,
    },
    filterChip: {
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      backgroundColor: theme.backgroundRoot,
      borderRadius: BorderRadius.md,
      borderWidth: 1,
      borderColor: theme.border,
    },
    filterChipActive: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    historyListContainer: {
      flex: 1,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: Spacing['2xl'],
    },
    loadingText: {
      marginTop: Spacing.md,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: Spacing['2xl'],
    },
    emptyText: {
      marginTop: Spacing.md,
    },
    historyItem: {
      padding: Spacing.lg,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    historyItemContent: {
      gap: Spacing.sm,
    },
    historyItemHeader: {
      gap: Spacing.sm,
    },
    historyItemTitle: {
      fontSize: 16,
      fontWeight: '600' as const,
    },
    historyItemMeta: {
      flexDirection: 'row',
      gap: Spacing.sm,
    },
    subjectTag: {
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      borderRadius: 8,
    },
    gradeTag: {
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      borderRadius: 8,
    },
    historyItemObjective: {
      lineHeight: 20,
    },
    historyItemFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    styleScrollWrapper: {
      height: 110,
    },
    styleScroll: {
      gap: Spacing.md,
    },
    styleOption: {
      width: 100,
      height: 100,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundTertiary,
      justifyContent: 'center',
      alignItems: 'center',
      gap: Spacing.sm,
      borderWidth: 2,
      borderColor: theme.borderLight,
    },
    styleOptionActive: {
      borderColor: theme.primary,
      boxShadow: '0px 4px 12px rgba(22, 120, 209, 0.3)',
    },
    styleOptionName: {
      fontSize: 12,
      fontWeight: '600' as const,
    },
    styleDescription: {
      marginTop: Spacing.sm,
      padding: Spacing.md,
      backgroundColor: theme.backgroundDefault,
      borderRadius: BorderRadius.lg,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    closeModalButton: {
      flex: 1,
      paddingVertical: Spacing.lg,
      backgroundColor: theme.textSecondary,
      borderRadius: BorderRadius.lg,
      alignItems: 'center',
    },
  });
};
