import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    scrollContent: {
      flexGrow: 1,
      backgroundColor: theme.backgroundRoot,
    },
    loadingContainer: {
      flex: 1,
      flexDirection: 'column',
    },
    quoteCarouselWrapper: {
      flex: 2,
      justifyContent: 'center',
    },
    progressContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: Spacing["2xl"],
      paddingBottom: Spacing.xl,
    },
    loadingText: {
      textAlign: 'center',
    },
    errorContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: Spacing.lg,
      gap: Spacing.md,
    },
    header: {
      marginBottom: Spacing.lg,
      paddingHorizontal: Spacing.lg,
      paddingTop: Spacing.xl,
    },
    section: {
      padding: Spacing.lg,
      borderRadius: BorderRadius.lg,
      marginBottom: Spacing.lg,
      marginHorizontal: Spacing.lg,
      borderWidth: 1.5,
      borderColor: theme.border,
      backgroundColor: theme.backgroundDefault,
      boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.04)',
    },
    sectionTitle: {
      marginBottom: Spacing.md,
      fontWeight: '700' as const,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.md,
    },
    regenerateButton: {
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      borderRadius: BorderRadius.md,
      borderWidth: 1.5,
      borderColor: theme.primary,
      backgroundColor: 'transparent',
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    objectiveContainer: {
      gap: Spacing.md,
    },
    objectiveCard: {
      padding: Spacing.lg,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundTertiary,
      borderLeftWidth: 4,
      borderLeftColor: theme.primary,
    },
    objectiveLabel: {
      marginBottom: Spacing.xs,
      fontWeight: '600' as const,
    },
    optionCard: {
      padding: Spacing.lg,
      borderRadius: BorderRadius.lg,
      marginBottom: Spacing.sm,
      borderWidth: 1.5,
      borderColor: theme.border,
      backgroundColor: theme.backgroundDefault,
    },
    optionCardSelected: {
      borderWidth: 2,
      borderColor: theme.primary,
      backgroundColor: theme.backgroundTertiary,
    },
    optionDescription: {
      marginTop: Spacing.sm,
      lineHeight: 22,
      fontSize: 15,
    },
    optionRationale: {
      marginTop: Spacing.sm,
      fontStyle: 'italic',
      fontSize: 13,
      color: theme.textMuted,
    },
    optionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: Spacing.xs,
    },
    optionTitle: {
      fontSize: 17,
      fontWeight: '600' as const,
    },
    checkBadge: {
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.xs,
      borderRadius: BorderRadius.sm,
      minWidth: 28,
      height: 28,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.primary,
    },
    buttonContainer: {
      marginTop: Spacing.xl,
      marginHorizontal: Spacing.lg,
      gap: Spacing.md,
      paddingBottom: Spacing['5xl'],
    },
    primaryButton: {
      backgroundColor: theme.primary,
      paddingVertical: Spacing.lg,
      paddingHorizontal: Spacing.xl,
      borderRadius: BorderRadius.lg,
      alignItems: 'center',
      height: 56,
      justifyContent: 'center',
      flexDirection: 'row',
      gap: Spacing.sm,
      boxShadow: '0px 4px 12px rgba(22, 120, 209, 0.35)',
    },
    secondaryButton: {
      backgroundColor: theme.backgroundDefault,
      paddingVertical: Spacing.lg,
      paddingHorizontal: Spacing.xl,
      borderRadius: BorderRadius.lg,
      alignItems: 'center',
      height: 56,
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: theme.border,
    },
    modalContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      padding: Spacing.xl,
    },
    modalContent: {
      width: '100%',
      maxWidth: 400,
      padding: Spacing.xl,
      borderRadius: BorderRadius.xl,
      gap: Spacing.xl,
      backgroundColor: theme.backgroundDefault,
      boxShadow: '0px 8px 24px rgba(0, 0, 0, 0.12)',
    },
    modalTitle: {
      textAlign: 'center',
      fontWeight: '700' as const,
    },
    progressBar: {
      width: '100%',
      height: 10,
      borderRadius: 5,
      backgroundColor: theme.backgroundTertiary,
      overflow: 'hidden',
    },
    progressFill: {
      height: '100%',
      borderRadius: 5,
      backgroundColor: theme.primary,
    },
    progressText: {
      marginTop: Spacing.md,
      textAlign: 'center',
      fontWeight: 'bold',
      fontSize: 24,
      color: theme.primary,
    },
    progressMessage: {
      marginTop: Spacing.xs,
      textAlign: 'center',
      fontSize: 15,
      color: theme.textSecondary,
    },
    errorButton: {
      backgroundColor: theme.primary,
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.xl,
      borderRadius: BorderRadius.lg,
      alignItems: 'center',
      height: 56,
      justifyContent: 'center',
      boxShadow: '0px 4px 12px rgba(22, 120, 209, 0.35)',
    },
  });
};
