import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    scrollContent: {
      flexGrow: 1,
      backgroundColor: theme.backgroundRoot,
    },
    header: {
      marginBottom: Spacing.xl,
      paddingHorizontal: Spacing.lg,
      paddingTop: Spacing.xl,
    },
    section: {
      marginBottom: Spacing.xl,
      borderRadius: BorderRadius.lg,
      padding: Spacing.lg,
      marginHorizontal: Spacing.lg,
      borderWidth: 1.5,
      borderColor: theme.border,
      backgroundColor: theme.backgroundDefault,
      boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.04)',
    },
    sectionTitle: {
      marginBottom: Spacing.md,
      fontWeight: '700' as const,
      fontSize: 18,
      color: theme.primary,
    },
    subSection: {
      marginBottom: Spacing.md,
    },
    infoRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.sm,
    },
    optionContainer: {
      marginBottom: Spacing.md,
      paddingBottom: Spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: theme.borderLight,
    },
    optionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.xs,
    },
    subTitle: {
      fontWeight: '600' as const,
    },
    rationale: {
      marginTop: Spacing.xs,
      fontSize: 13,
      color: theme.textSecondary,
      fontStyle: 'italic',
    },
    markdownContainer: {
      padding: Spacing.md,
      backgroundColor: theme.backgroundTertiary,
      borderRadius: BorderRadius.md,
      marginTop: Spacing.sm,
    },
    adjustButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    adjustButtonText: {
      fontWeight: '600' as const,
    },
    sectionAdjustButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.sm,
      marginTop: Spacing.md,
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.lg,
      backgroundColor: 'transparent',
      borderRadius: BorderRadius.lg,
      borderWidth: 1.5,
      borderColor: theme.primary,
    },
    sectionAdjustButtonText: {
      fontWeight: '600' as const,
    },
    actionButtons: {
      flexDirection: 'row',
      gap: Spacing.md,
      marginTop: Spacing.xl,
      paddingHorizontal: Spacing.lg,
      paddingBottom: Spacing['5xl'],
    },
    actionButton: {
      flex: 1,
      paddingVertical: Spacing.lg,
      paddingHorizontal: Spacing.xl,
      borderRadius: BorderRadius.lg,
      alignItems: 'center',
      height: 56,
      justifyContent: 'center',
      flexDirection: 'row',
      gap: Spacing.sm,
    },
    backButton: {
      backgroundColor: theme.backgroundDefault,
      borderWidth: 1.5,
      borderColor: theme.border,
    },
    saveButton: {
      backgroundColor: theme.primary,
      boxShadow: '0px 4px 12px rgba(22, 120, 209, 0.35)',
    },
    // Loading styles
    loadingContainer: {
      flex: 1,
      flexDirection: 'column',
    },
    quoteCarouselWrapper: {
      flex: 2,
      justifyContent: 'center',
    },
    loadingText: {
      marginTop: Spacing.lg,
      fontSize: 16,
      fontWeight: '600' as const,
    },
    loadingMessage: {
      marginTop: Spacing.md,
      textAlign: 'center',
      fontSize: 15,
      color: theme.textSecondary,
    },
    progressContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: Spacing["2xl"],
      paddingBottom: Spacing.xl,
    },
    progressBar: {
      width: '100%',
      height: 10,
      backgroundColor: theme.backgroundTertiary,
      borderRadius: 5,
      overflow: 'hidden',
    },
    progressFill: {
      height: '100%',
      backgroundColor: theme.primary,
      borderRadius: 5,
    },
    progressText: {
      marginTop: Spacing.md,
      textAlign: 'center',
      fontWeight: '700' as const,
      fontSize: 24,
      color: theme.primary,
    },
    // Modal styles
    modalContainer: {
      flex: 1,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 5,
    },
    modalContentWrapper: {
      width: '90%',
      maxWidth: 500,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContent: {
      width: '100%',
      maxHeight: '90%',
      minHeight: 400,
      borderRadius: BorderRadius.xl,
      overflow: 'visible',
      backgroundColor: theme.backgroundDefault,
      flexDirection: 'column',
      flex: 0,
      elevation: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 12,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: Spacing.lg,
      borderBottomWidth: 1.5,
      borderBottomColor: theme.border,
      flexShrink: 0,
    },
    modalBody: {
      backgroundColor: theme.backgroundDefault,
      flex: 1,
      minHeight: 0,
    },
    modalBodyContent: {
      padding: Spacing.lg,
      paddingBottom: Spacing['2xl'],
      flexGrow: 1,
    },
    modalSectionTitle: {
      marginBottom: Spacing.sm,
      fontWeight: '600' as const,
    },
    currentOptionCard: {
      backgroundColor: theme.backgroundTertiary,
      borderRadius: BorderRadius.lg,
      padding: Spacing.lg,
      marginBottom: Spacing.lg,
      borderLeftWidth: 4,
      borderLeftColor: theme.primary,
    },
    currentOptionDesc: {
      marginTop: Spacing.xs,
      lineHeight: 22,
    },
    adjustmentInput: {
      borderWidth: 1.5,
      borderColor: theme.border,
      borderRadius: BorderRadius.lg,
      padding: Spacing.md,
      minHeight: 120,
      marginBottom: Spacing.sm,
      backgroundColor: theme.backgroundDefault,
      fontSize: 16,
      color: theme.textPrimary,
    },
    inputContainer: {
      flexDirection: 'column',
      gap: Spacing.sm,
      marginBottom: Spacing.sm,
    },
    voiceButton: {
      height: 56,
      borderRadius: BorderRadius.lg,
      borderWidth: 1.5,
      borderColor: theme.primary,
      backgroundColor: theme.backgroundDefault,
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
      gap: Spacing.sm,
      paddingHorizontal: Spacing.lg,
    },
    voiceButtonText: {
      fontWeight: '600' as const,
    },
    voiceButtonRecording: {
      backgroundColor: '#ef4444',
      borderColor: '#ef4444',
    },
    voiceButtonRecognizing: {
      opacity: 0.6,
    },
    hint: {
      lineHeight: 20,
      fontSize: 13,
      color: theme.textSecondary,
    },
    modalFooter: {
      flexDirection: 'row',
      gap: Spacing.md,
      padding: Spacing.lg,
      borderTopWidth: 1.5,
      borderTopColor: theme.border,
      flexShrink: 0,
    },
    cancelButton: {
      flex: 1,
      paddingVertical: Spacing.md,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundDefault,
      borderWidth: 1.5,
      borderColor: theme.border,
      alignItems: 'center',
      height: 52,
      justifyContent: 'center',
    },
    confirmButton: {
      flex: 1,
      paddingVertical: Spacing.md,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.primary,
      alignItems: 'center',
      height: 52,
      justifyContent: 'center',
      boxShadow: '0px 4px 12px rgba(22, 120, 209, 0.35)',
    },
    // Date picker styles
    dateValueContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    dateIcon: {
      marginLeft: Spacing.xs,
    },
  });
};
